### ISSUE TITLE
dotjs no longer runs in non-https mode.

### ISSUE THREAD

**Issue by nicksergeant** [defunkt/dotjs#116]
https://localhost:3131 displays:

![http://i.imgur.com/s54cYkM.png](http://i.imgur.com/s54cYkM.png)

http://localhost:3131 404s:

![http://i.imgur.com/zkZdJHD.png](http://i.imgur.com/zkZdJHD.png)

This makes dotjs not work on non-https URLs.

**Comment by paleite** [comment]
I'm having the same issue 😔
