### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by starzonmyarmz** [defunkt/dotjs#20]
Right now I'd like it to work on domain and all of it's sub domains - examples:

foo.domain.com
bar.domain.com

It seems as if I need to have two seperate js files:

foo.domain.com.js
bar.domain.com.js

It would be cool if there were wildcard support where all subdomains were included by default by having a file: domain.com.js and then if you want target sub domains only you would have foo.domain.com.js

Though I suppose this could be achieved by looking for regex's in the url using javascript...

**Comment by tsbay77** [comment]
> Right now I'd like it to work on domain and all of it's sub domains - examples:
> 
> foo.domain.com bar.domain.com
> 
> It seems as if I need to have two seperate js files:
> 
> foo.domain.com.js bar.domain.com.js
> 
> It would be cool if there were wildcard support where all subdomains were included by default by having a file: domain.com.js and then if you want target sub domains only you would have foo.domain.com.js
> 
> Though I suppose this could be achieved by looking for regex's in the url using javascript...

**Comment by tsbay77** [comment]
```c++

```
